
name: 'side_income'
version: '1.0.0'
config-version: 2

profile: 'bigQuery'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models:
    side_income:
        staging:
            materialized: table
        marts:
            core:
                materialized: table
            jobs:
                materialized: table
            portfolio:
                materialized: table
