
version: 2

models:

    - name: stg_job_app_ratings
      description: "staging table for app ratings"
      columns:
        - name: ratings_id
          description: "unique id of ratings at the start of a work day"
          tests:
            - unique
            - not_null
        - name: job_title_id
          description: "unique id of the job performed"
          tests:
            - not_null
        - name: ratings_date
          description: "date during which specific ratings showed on app"
          tests:
            - not_null
        - name: star_rating
          description: "overall # stars. Summary of rating"
          tests:
            - not_null
        - name: acceptance_rating
          description: "doordash stat: # deliveries shown that you accept"
          tests:
            - not_null
        - name: completion_rating
          description: "doordash stat: % of last 100 deliveries you complete after accepting"
          tests:
            - not_null
        - name: on_time_rating
          description: "doordash stat: % of your last 100 deliveries you completed on time or early"
          tests:
            - not_null
        - name: friendliness_rating
          description: "lyft stat: # of passengers that rated you as being friendly"
          tests:
            - not_null
        - name: driving_rating
          description: "lyft stat: # of passengers that rated your driving as good"
          tests:
            - not_null
        - name: car_rating
          description: "lyft stat: # of passengers that rated your car as being nice and clean"
          tests:
            - not_null
        - name: above_beyond_rating
          description: "lyft stat: # of passengers that rated you as going above and beyond (whatever that means)"
          tests:
            - not_null

    - name: stg_job_business_stats
      description: "staging table for stats on business delivered or service provided"
      columns:
        - name: business_id
          description: "unique id of business food picked up from or service delivered"
          tests:
            - unique
            - not_null
        - name: business_name
          description: "unique name of business food picked up from or service delivered"
          tests:
            - unique
            - not_null
        - name: business_star_rating
          description: "ratings a business recieved from users on the user facing app (not driver app; what users see)"
        - name: num_business_rating
          description: "# of ratings a business recieved from users"
        - name: business_price_rating
          description: "# dollar signs ($) users see when placing order: 1 $ is cheapest"
        - name: business_food_type
          description: "crude labeling of typical food served at a restauraunt/business"

    - name: stg_job_hours_worked
      description: "staging table for hours worked on a particula day in a particular app"
      columns:
        - name: hours_worked_id
          description: "unique id of hours worked on a day in an app"
          tests:
            - unique
            - not_null
        - name: job_title_id
          description: "unique id of service provided"
          tests:
            - not_null
        - name: work_date
          description: "date of work"
          tests:
            - not_null
        - name: hours_worked
          description: "# hours worked on a day in an app"
          tests:
            - not_null
        - name: minutes_worked
          description: "# minutes worked on a day in an app"
          tests:
            - not_null
        - name: total_time_worked
          description: "total time worked in user friendly format (decimal)"
          tests:
            - not_null

    - name: stg_job_job
      description: "staging table for job titles"
      columns:
        - name: job_title_id
          description: "unique id of service provided"
          tests:
            - unique
            - not_null
        - name: service_title
          description: "unique name of service provided"
          tests:
            - unique
            - not_null

    - name: stg_job_mileage
      description: "staging table for side income mileage"
      columns:
        - name: mileage_id
          description: "unique id for the total mileage driven for a given job title for the day"
          tests:
            - unique
            - not_null
        - name: job_title_id
          description: "id for the job title driven"
          tests:
            - not_null
        - name: mileage_date
          description: "date mileage was tracked"
          tests:
            - not_null
        - name: total_mileage
          description: "total mileage driven for a job on a day"
          tests:
            - not_null

    - name: stg_job_payouts
      description: "staging table for side income payouts"
      columns:
        - name: payout_id
          description: "payout id for an individual service offered to a client"
          tests:
            - unique
            - not_null
        - name: job_title_id
          description: "unique id for the job title of a service offered"
          tests:
            - not_null
            # TODO: add a test to enforce relationship with the job table
        - name: completed_date
          description: "date of job completion"
          tests:
            - not_null
        - name: business_service
          description: "name of service provided to the customer or business name if food delivered"
          tests:
            - not_null
        - name: std_earnings
          description: "base pay before tips and bonus"
          tests:
            - not_null
        - name: bonus_earnings
          description: "additional earnings: usually indicates extra service provided or demand for service was high"
          tests:
            - not_null
        - name: tip_earnings
          description: "generous customers leave a tip for rideshare/delivery service, scumbags don't"
          tests:
            - not_null
        - name: other_earnings
          description: "misc earnings while active, could include: cancelation fees, non-job associated bonuses etc..."
        - name: completion_notes
          description: "notes taken to provide clerity on an obscure or non-standard payout"

    - name: stg_robinhood_transactions
      description: "staging table for robinhood transactions"
      columns:
        - name: rh_id
          description: 'unique transaction id for robinhood'
          tests:
            - unique
            - not_null
        - name: ticker_symbol
          description: 'stock ticker symbol'
          tests:
            - not_null
        - name: purchase_date
          description: 'day a certain ticker symbol was purchased'
          tests:
            - not_null
        - name: qt_share_purchased
          description: 'total number of shares purchased in the transaction'
          tests:
            - not_null
        - name: avg_price
          description: 'avg share price for a transaction block'
          tests:
            - not_null
        - name: cum_quantity_owned
          description: 'total number shares currently owned for symbol at date'
          tests:
            - not_null
        - name: cost_basis
          description: 'average price of purchase over all purchases after current transaction'
          tests:
            - not_null
